# Generated by Django 6.0.4 on 2026-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
