# Generated by Django 6.0.4 on 2026-04-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_date', 'appointment_time', 'service')},
        ),
    ]
